version: '3.9'

services:
  facturion_database:
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file:
      - ./database/.env
    container_name: facturion_db
    ports:
      - 5432:5432
    networks:
      - bst_network
    volumes:
      - ./database/volume:/var/lib/postgresql/data:rw
  facturion_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    container_name: facturion_backend
    expose:
      - 8000
    ports:
      - 8000:8000
    networks:
      - bst_network
    depends_on:
      - facturion_database
    links:
      - facturion_database:facturion_database
  facturion_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file: 
      - ./frontend/.env
    container_name: facturion_frontend
    restart: always
    expose:
      - "80"  # 3000
    depends_on:
      - facturion_backend
    ports:
      - "80:3000" # 3000:3000
    networks:
      - bst_network

networks:
  bst_network:
    driver: bridge
